[package]
name    = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow     = "1.0"
env_logger = "0.9"
form       = "0.10"
log        = "0.4"
strum      = { version = "0.24", features = ["derive"] }
svd2rust   = "0.25"
svdtools   = "0.2"
toml       = "0.5"

[dependencies.clap]
version  = "4.0"
features = ["derive"]
